import esbuild from "esbuild";
import process from "node:process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(fileURLToPath(import.meta.url));

/** Vault that Obsidian actually opens; the plugin is installed straight into it. */
const VAULT_PLUGIN_DIR = path.resolve(
  root,
  "..",
  "插件开发",
  ".obsidian",
  "plugins",
  "enhanced-graph",
);

/**
 * Where the plugin bundle is written.
 *
 * Defaults to the repository root, which is what every Obsidian sample plugin
 * does and what the directory's build verification expects: it builds the repo
 * and looks for a `main.js` next to `manifest.json`. Writing to the vault by
 * default meant that check found nothing, and the plugin was reported as
 * unbuildable even though the build worked.
 *
 * `--vault` opts back in to the copy Obsidian actually loads, for local
 * development; `--out=<dir>` overrides both.
 */
const outArg = process.argv.find((arg) => arg.startsWith("--out="));
const OUT_DIR = outArg
  ? path.resolve(root, outArg.slice("--out=".length))
  : process.argv.includes("--vault")
    ? VAULT_PLUGIN_DIR
    : root;

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin

Enhanced Graph — Copyright (C) 2026 lkhfrgc

This program is free software: you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation, version 3 of the License.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <https://www.gnu.org/licenses/>.

Third-party notices: see THIRD-PARTY-NOTICES.md
*/
`;

const isProduction = process.argv.includes("production");
const isWatch = process.argv.includes("--watch");
const isHarness = process.argv.includes("harness");

/** Shared by both the Obsidian bundle and the browser harness bundle. */
const shared = {
  bundle: true,
  target: "es2022",
  logLevel: "info",
  sourcemap: isProduction ? false : "inline",
  treeShaking: true,
  define: {
    "process.env.NODE_ENV": JSON.stringify(isProduction ? "production" : "development"),
  },
};

/** Node/Electron builtins and Obsidian-provided modules must never be bundled. */
const obsidianExternals = [
  "obsidian",
  "electron",
  "@electron/remote",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  "child_process",
  "crypto",
  "fs",
  "http",
  "https",
  "os",
  "path",
  "stream",
  "url",
  "util",
  "zlib",
];

/**
 * The bundled libraries' notices, attached to the END of the output.
 *
 * `main.js` contains substantial portions of all five, and MIT requires the
 * notice to accompany them. esbuild can only keep the `/*! *\/` blocks a
 * dependency happened to ship — most ship none — so the full text is appended
 * here, read from THIRD-PARTY-NOTICES.md so there is one source of truth.
 */
const NOTICES_FILE = path.join(root, "THIRD-PARTY-NOTICES.md");
const noticesFooter = fs.existsSync(NOTICES_FILE)
  ? `/*!\n${fs
      .readFileSync(NOTICES_FILE, "utf8")
      .replace(/\*\//g, "*\\/")
      .trim()}\n*/\n`
  : "";

function copyStaticAssets() {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  // THIRD-PARTY-NOTICES.md travels too: the bundle points at it by name, and a
  // pointer to a file that is not in the folder is worse than no pointer.
  for (const file of ["manifest.json", "styles.css", "THIRD-PARTY-NOTICES.md"]) {
    const from = path.join(root, file);
    const to = path.join(OUT_DIR, file);
    // `--out=.` makes source and destination the same file; copying onto itself
    // throws, and there is nothing to do anyway.
    if (fs.existsSync(from) && from !== to) {
      fs.copyFileSync(from, to);
    }
  }
}

function createPluginContext() {
  return esbuild.context({
    ...shared,
    entryPoints: [path.join(root, "src", "main.ts")],
    outfile: path.join(OUT_DIR, "main.js"),
    format: "cjs",
    platform: "browser",
    external: obsidianExternals,
    banner: { js: banner },
    // Keep the bundled libraries' /*! ... */ licence blocks in the output. esbuild
    // drops comments, and MIT requires the notice to travel with the code;
    // THIRD-PARTY-NOTICES.md carries the full texts either way.
    legalComments: "eof",
    footer: { js: noticesFooter },
    plugins: [
      {
        name: "copy-static-assets",
        setup(build) {
          build.onEnd((result) => {
            if (result.errors.length === 0) copyStaticAssets();
          });
        },
      },
    ],
  });
}

if (isHarness) {
  // Browser harness: same view code, but `obsidian` resolves to a stub and the
  // output is an ES module the headless test page can import directly.
  const harnessContext = await esbuild.context({
    ...shared,
    absWorkingDir: root,
    entryPoints: [path.join(root, "harness", "entry.ts")],
    outfile: path.join(root, "harness", "bundle.js"),
    format: "esm",
    platform: "browser",
    alias: { obsidian: path.join(root, "harness", "obsidian-stub.ts") },
  });
  await harnessContext.rebuild();
  // Disposing is what lets the esbuild service shut down; without it the
  // process lingers after the bundle is written.
  await harnessContext.dispose();
  console.log("harness bundle written to harness/bundle.js");
} else if (isWatch) {
  const pluginContext = await createPluginContext();
  await pluginContext.watch();
  console.log(`watching… output → ${OUT_DIR}`);
} else {
  const pluginContext = await createPluginContext();
  await pluginContext.rebuild();
  await pluginContext.dispose();
  console.log(`built → ${path.join(OUT_DIR, "main.js")}`);
}
